title: AI4FACD
description: AI for Fully-Automated Chip Design
baseurl: ""
url: "https://ai4facd.github.io"

theme: jekyll-nagymaros

indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
